---
# GitHub: Continuous Integration Action
# codejedi365 | MIT LICENSE | 22 Aug 2021
name: CI

on:
  push:
    branches: 
      - main
      - release/*
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Source Code
    runs-on: ubuntu-latest
    env:
        node-version: 12.x
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    name: Build Code Bundle
    runs-on: ubuntu-latest
    env:
        node-version: 12.x
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build bundle
        run: npm run build:prod
      
      - name: Upload bundle
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist-bundle
          path: dist/*
          if-no-files-found: error
          retention-days: 1

  test:
    name: Test on NodeJS v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download bundle
        uses: actions/download-artifact@v2
        with:
          name: dist-bundle
          path: dist/

      - name: execute tests
        env: 
          NODE_ENV: production
        run: npm run test:unit
